version: '2'
services:
  web:
    build:
      context: .
    restart: always
#    ports:
#     - "5000:5000"
    depends_on:
      - redis
    volumes:
      - .:/flask-app
    command: 'supervisord'
  redis:
    image: redis
